SCREEN_HEIGHT = 650
SCREEN_WIDTH = 810

MIN_BOARD_HEIGHT = 6
MIN_BOARD_WIDTH = 6
START_SNAKE_SIZE = 3

BLOCK_SIZE = 30
HOW_MANY_BLOCKS_WIDTH = 20
HOW_MANY_BLOCKS_HEIGHT = 15
GAP_SIZE = 10

BACKGROUND_COLOR = (26, 26, 28)
BORDER_COLOR = (255, 191, 94)
SNAKE_COLOR = (121, 62, 16, 100)
PREY_COLOR = (72, 73, 84)
OPAQUE_ALPHA = 210
HSV_STEP = 10

ACCELERATION_INTERVAL = 5
ACCELERATION = 2
PLAYER_SPEED = 0.2

FONT = "freesansbold.ttf"
TEXT_COLOR = (255, 255, 255)
GAME_OVER = "GAME OVER"
GAME_OVER_SIZE = 60
GAME_OVER_POSITION = (SCREEN_WIDTH // 2, 3 * SCREEN_HEIGHT // 15)
SCORE_SIZE = 32
YOUR_SCORE = "YOUR SCORE:"
HIGH_SCORE = "HIGH SCORE:"
YOUR_SCORE_POSITION = (SCREEN_WIDTH // 2, 5 * SCREEN_HEIGHT // 15)
YOUR_SCORE_SCORE_POSITION = (SCREEN_WIDTH // 2, 6 * SCREEN_HEIGHT // 15)
HIGH_SCORE_POSITION = (SCREEN_WIDTH // 2, 8 * SCREEN_HEIGHT // 15)
HIGH_SCORE_SCORE_POSITION = (SCREEN_WIDTH // 2, 9 * SCREEN_HEIGHT // 15)
CONTINUE = "Press R to try again or Q to quit."
CONTINUE_SIZE = 20
CONTINUE_POSITION = (SCREEN_WIDTH // 2, 11 * SCREEN_HEIGHT // 15)
SCORE = "SCORE: "
SCORE_POSITION = (
    SCREEN_WIDTH // 40,
    SCREEN_HEIGHT - SCREEN_HEIGHT // 17,
)
SCORE_SCORE_POSITION = (SCORE_POSITION[0] + SCREEN_WIDTH // 5, SCORE_POSITION[1])

FPS = 60

SAVEFILE = "high_score.txt"